

security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: my-trusted-client
      clientSecret: secret
      accessTokenUri: http://localhost:2222/oauth/token
      userAuthorizationUri: http://localhost:2222/oauth/authorize
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
        userInfoUri: http://localhost:2222/oauth/authorize
